rem ESTE SCRIPT VAI FAZER O SEU CÓDIGO PYTHON SER EXECUTADO AUTOMATICAMENTE
@echo off
rem ABAIXO O CAMINHO ONDE ESTÁ O SEU SCRIPT PYTHON
cd "C:\Users\SEU_USUARIO\Documents\python\yt-download-podcast"
python youtube.py
pause
rem CONFIGURE ESTE SCRIPT PRA SER EXECUTADO QUANDO O SEU WINDOWS INICAR